const state = {
    selectedFiles: [],
    currentUser: null,
    realtimeChannel: null,
    realtimeReconnectTimer: null,
    realtimePingTimer: null,
    realtimeReconnectAttempts: 0,
    realtimeShouldReconnect: false,
    realtimeAuthKey: null,
    realtimeSummaryFreshTimer: null,
    currentTimelineTab: 'foryou',
    replyingTo: null,
    quotingPost: null,
    newIconDataUrl: null,
    resetIconToDefault: false,
    newHeaderDataUrl: null,
    resetHeaderToDefault: false,
    settingsSaveInFlight: false,
    settingsSaveQueued: false,
    activeDmId: null,
    lastRenderedMessageId: null,
    pendingRealtimeDmMessages: new Map(),
    activeDmMemberIds: [],
    recommendedUsersCache: null,
    publicProfileCache: new Map(),
    allUsersCache: new Map(),
    pwaRegistrationPromise: null,
    isLoadingMore: false,
    postLoadObserver: undefined,
    currentSearchTab: 'posts',
    currentPagination: { page: 0, hasMore: true, type: null, options: {} },
    isDarkmode: window.matchMedia('(prefers-color-scheme: dark)').matches,
    emoji_picker_theme: 'light',
    dmE2EPublicKeyCache: new Map(),
    dmE2ERegisteredUsers: null,
    dmUnreadCounts: new Map(),
};

function makeAccessors(key) {
    const capitalized = key.charAt(0).toUpperCase() + key.slice(1);
    return {
        [`get${capitalized}`]: () => state[key],
        [`set${capitalized}`]: (value) => {
            state[key] = value;
            return state[key];
        },
    };
}

const accessors = {};
for (const key of Object.keys(state)) {
    Object.assign(accessors, makeAccessors(key));
}

export const {
    getSelectedFiles,
    setSelectedFiles,
    getCurrentUser,
    setCurrentUser,
    getRealtimeChannel,
    setRealtimeChannel,
    getRealtimeReconnectTimer,
    setRealtimeReconnectTimer,
    getRealtimePingTimer,
    setRealtimePingTimer,
    getRealtimeReconnectAttempts,
    setRealtimeReconnectAttempts,
    getRealtimeShouldReconnect,
    setRealtimeShouldReconnect,
    getRealtimeAuthKey,
    setRealtimeAuthKey,
    getRealtimeSummaryFreshTimer,
    setRealtimeSummaryFreshTimer,
    getCurrentTimelineTab,
    setCurrentTimelineTab,
    getReplyingTo,
    setReplyingTo,
    getQuotingPost,
    setQuotingPost,
    getNewIconDataUrl,
    setNewIconDataUrl,
    getResetIconToDefault,
    setResetIconToDefault,
    getNewHeaderDataUrl,
    setNewHeaderDataUrl,
    getResetHeaderToDefault,
    setResetHeaderToDefault,
    getSettingsSaveInFlight,
    setSettingsSaveInFlight,
    getSettingsSaveQueued,
    setSettingsSaveQueued,
    getActiveDmId,
    setActiveDmId,
    getLastRenderedMessageId,
    setLastRenderedMessageId,
    getPendingRealtimeDmMessages,
    setPendingRealtimeDmMessages,
    getActiveDmMemberIds,
    setActiveDmMemberIds,
    getRecommendedUsersCache,
    setRecommendedUsersCache,
    getPublicProfileCache,
    setPublicProfileCache,
    getAllUsersCache,
    setAllUsersCache,
    getPwaRegistrationPromise,
    setPwaRegistrationPromise,
    getIsLoadingMore,
    setIsLoadingMore,
    getPostLoadObserver,
    setPostLoadObserver,
    getCurrentSearchTab,
    setCurrentSearchTab,
    getCurrentPagination,
    setCurrentPagination,
    getIsDarkmode,
    setIsDarkmode,
    getEmoji_picker_theme,
    setEmoji_picker_theme,
    getDmE2EPublicKeyCache,
    setDmE2EPublicKeyCache,
    getDmE2ERegisteredUsers,
    setDmE2ERegisteredUsers,
    getDmUnreadCounts,
    setDmUnreadCounts,
} = accessors;
